### ISSUE TITLE
WSMan Exception On Windows Server 2016

### ISSUE THREAD

**Issue by PrahlM93** [test-kitchen/kitchen-dsc#17]
Hello,
When running "kitchen converge" on a Windows Server 2016 TP5 guest, I get the error posted below after the "Staging DSC configuration script for copy to the SUT". I think this is failing when it is applying the LCM configuration. I believe the issue is with the underlying winrm gem, but I'd like your thoughts first.

```
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [[WSMAN ERROR CODE: 2150858767]: <f:WSManFault Code='2150858767' Machine='192.168.1.150' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The WS-Management service cannot process the request. The XML contains an invalid timeout field in the SOAP header: 60. </f:Message></f:WSManFault>]
D      ---Nested Exception---
D      Class: WinRM::WinRMWSManFault
D      Message: [WSMAN ERROR CODE: 2150858767]: <f:WSManFault Code='2150858767' Machine='192.168.1.150' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The WS-Management service cannot process the request. The XML contains an invalid timeout field in the SOAP header: 60. </f:Message></f:WSManFault>
D      ------Backtrace-------
D      C:/Users/mprahl/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-1.8.1/lib/winrm/http/response_handler.rb:64:in `raise_if_wsman_fault'
D      C:/Users/mprahl/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-1.8.1/lib/winrm/http/response_handler.rb:51:in `raise_if_error'
D      C:/Users/mprahl/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-1.8.1/lib/winrm/http/response_handler.rb:35:in `parse_to_xml'
D      C:/Users/mprahl/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-1.8.1/lib/winrm/http/transport.rb:53:in `send_request'
D      C:/Users/mprahl/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-1.8.1/lib/winrm/winrm_service.rb:492:in `send_message'
D      C:/Users/mprahl/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-1.8.1/lib/winrm/winrm_service.rb:153:in `open_shell'
D      C:/Users/mprahl/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-transport-1.0.3/lib/winrm/transport/command_executor.rb:78:in `open'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/winrm.rb:257:in `block in establish_shell'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/winrm.rb:369:in `retryable'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/winrm.rb:255:in `establish_shell'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/winrm.rb:395:in `session'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/winrm.rb:271:in `execute_with_exit_code'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/winrm.rb:115:in `execute'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/provisioner/base.rb:67:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/base.rb:86:in `initialize'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/winrm.rb:492:in `new'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/winrm.rb:492:in `create_new_connection'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/transport/winrm.rb:84:in `connection'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/provisioner/base.rb:66:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:373:in `block in converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:495:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:495:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:460:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:459:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:369:in `converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:347:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:347:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:138:in `converge'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command.rb:176:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `block in create_with_logging_context'
D      ----------------------
```

**Comment by mwrock** [comment]
Hmm. very strage. Can you tell me what verion of the winrm gem you have installed?

**Comment by PrahlM93** [comment]
@mwrock, I have 1.8.1 and 1.6.1 installed but it seems to be using 1.8.1 based on the logs.

**Comment by smurawski** [comment]
@PrahlM93 Can you provide a gist with an attempt to converge with `-l debug` added?

**Comment by PrahlM93** [comment]
Hi @smurawski, here is what I get:
https://gist.github.com/PrahlM93/7db97d666bcdf0917339389fa2be7be2

**Comment by smurawski** [comment]
@PrahlM93 Ah ha, you are using a pretty old version of Test-Kitchen that relies on the deprecated winrm-s/winrm-transport combo.  winrm-s monkey-patches winrm and that lead to some funkiness in winrm-transport occasionally.

Test-Kitchen 1.6 or newer (current is 1.8) have moved to newer version of the winrm gem, which has native support for negotiate auth, and winrm-fs which has the current file handling code (winrm-transport has been deprecated).

**Comment by PrahlM93** [comment]
@smurawski Thanks for advice. Updating Test-Kitchen did the trick!
